import { describe, it, expect } from 'vitest'
import { formatJsonReport } from '../src/report/json.js'
import { formatMarkdownReport } from '../src/report/markdown.js'
import { formatTerminalReport } from '../src/report/terminal.js'
import type { SessionSnapshot } from '../src/core/types.js'
import { emptyUsage } from '../src/core/pricing.js'

const snapshot: SessionSnapshot = {
  teamName: 'test-team',
  sessionId: 'test-session-001',
  startedAt: 1700000000000,
  lastUpdatedAt: 1700003600000, // +1 hour
  finalized: true,
  agents: [
    {
      agentId: 'lead',
      name: 'team-lead',
      model: 'opus',
      tokenUsage: {
        input_tokens: 100_000,
        output_tokens: 50_000,
        cache_creation_input_tokens: 0,
        cache_read_input_tokens: 500_000,
      },
      cost: 5.5,
      status: 'shutdown',
    },
    {
      agentId: 'worker1',
      name: 'syntax-fixer',
      model: 'haiku',
      tokenUsage: {
        input_tokens: 200_000,
        output_tokens: 100_000,
        cache_creation_input_tokens: 0,
        cache_read_input_tokens: 0,
      },
      cost: 0.56,
      status: 'done',
    },
  ],
  tasks: [
    {
      id: '1',
      subject: 'Fix syntax errors',
      description: '',
      activeForm: '',
      owner: 'syntax-fixer',
      status: 'completed',
      blocks: [],
      blockedBy: [],
    },
    {
      id: '2',
      subject: 'Run regression tests',
      description: '',
      activeForm: '',
      owner: '',
      status: 'pending',
      blocks: [],
      blockedBy: [],
    },
  ],
  totalCost: 6.06,
  totalTokens: {
    input_tokens: 300_000,
    output_tokens: 150_000,
    cache_creation_input_tokens: 0,
    cache_read_input_tokens: 500_000,
  },
  alerts: [
    {
      level: 'warning',
      message: 'Budget: 80% consumed',
      timestamp: 1700002000000,
    },
  ],
}

describe('formatJsonReport', () => {
  it('returns valid JSON', () => {
    const output = formatJsonReport(snapshot)
    const parsed = JSON.parse(output)
    expect(parsed.teamName).toBe('test-team')
    expect(parsed.agents).toHaveLength(2)
    expect(parsed.totalCost).toBe(6.06)
  })

  it('is pretty-printed with 2 spaces', () => {
    const output = formatJsonReport(snapshot)
    expect(output).toContain('  "teamName"')
  })
})

describe('formatMarkdownReport', () => {
  it('contains markdown header', () => {
    const output = formatMarkdownReport(snapshot)
    expect(output).toContain('# ccx Report: test-team')
  })

  it('contains summary table', () => {
    const output = formatMarkdownReport(snapshot)
    expect(output).toContain('| Session |')
    expect(output).toContain('test-session-001')
    expect(output).toContain('finalized')
  })

  it('contains agents table', () => {
    const output = formatMarkdownReport(snapshot)
    expect(output).toContain('## Agents')
    expect(output).toContain('team-lead')
    expect(output).toContain('syntax-fixer')
    expect(output).toContain('**TOTAL**')
  })

  it('contains tasks table', () => {
    const output = formatMarkdownReport(snapshot)
    expect(output).toContain('## Tasks')
    expect(output).toContain('Fix syntax errors')
    expect(output).toContain('syntax-fixer')
  })

  it('contains alerts', () => {
    const output = formatMarkdownReport(snapshot)
    expect(output).toContain('## Alerts')
    expect(output).toContain('Budget: 80% consumed')
  })

  it('contains footer', () => {
    const output = formatMarkdownReport(snapshot)
    expect(output).toContain('Generated by ccx')
  })

  it('handles snapshot with no tasks', () => {
    const noTasks: SessionSnapshot = { ...snapshot, tasks: [] }
    const output = formatMarkdownReport(noTasks)
    expect(output).not.toContain('## Tasks')
  })

  it('handles snapshot with no alerts', () => {
    const noAlerts: SessionSnapshot = { ...snapshot, alerts: [] }
    const output = formatMarkdownReport(noAlerts)
    expect(output).not.toContain('## Alerts')
  })
})

describe('formatTerminalReport', () => {
  it('contains team name header', () => {
    const output = formatTerminalReport(snapshot)
    expect(output).toContain('test-team')
  })

  it('contains agent names', () => {
    const output = formatTerminalReport(snapshot)
    expect(output).toContain('team-lead')
    expect(output).toContain('syntax-fixer')
  })

  it('contains task subjects', () => {
    const output = formatTerminalReport(snapshot)
    expect(output).toContain('Fix syntax errors')
    expect(output).toContain('Run regression tests')
  })

  it('contains cost info', () => {
    const output = formatTerminalReport(snapshot)
    expect(output).toContain('$6.06')
  })

  it('contains alert messages', () => {
    const output = formatTerminalReport(snapshot)
    expect(output).toContain('Budget: 80% consumed')
  })

  it('shows duration', () => {
    const output = formatTerminalReport(snapshot)
    expect(output).toContain('1h 0m')
  })
})
