/**
 * Markdown report formatter
 */
import type { SessionSnapshot } from '../core/types.js'
import { formatCost, formatTokens, totalTokenCount } from '../core/pricing.js'

export function formatMarkdownReport(snapshot: SessionSnapshot): string {
  const lines: string[] = []
  const elapsed = formatDuration(snapshot.lastUpdatedAt - snapshot.startedAt)
  const startedAt = new Date(snapshot.startedAt).toISOString()

  lines.push(`# ccx Report: ${snapshot.teamName}`)
  lines.push('')
  lines.push(`| Field | Value |`)
  lines.push(`|-------|-------|`)
  lines.push(`| Session | \`${snapshot.sessionId}\` |`)
  lines.push(`| Started | ${startedAt} |`)
  lines.push(`| Duration | ${elapsed} |`)
  lines.push(`| Status | ${snapshot.finalized ? 'finalized' : 'active'} |`)
  lines.push(`| Total Cost | **${formatCost(snapshot.totalCost)}** |`)
  lines.push(`| Agents | ${snapshot.agents.length} |`)
  lines.push(`| Tasks | ${snapshot.tasks.length} |`)
  lines.push('')

  // Agents
  lines.push(`## Agents`)
  lines.push('')
  lines.push(`| Name | Model | Status | Tokens | Cost |`)
  lines.push(`|------|-------|--------|--------|------|`)

  for (const agent of snapshot.agents) {
    const tokens = formatTokens(totalTokenCount(agent.tokenUsage))
    lines.push(`| ${agent.name} | ${agent.model} | ${agent.status} | ${tokens} | ${formatCost(agent.cost)} |`)
  }

  const totalTokens = formatTokens(totalTokenCount(snapshot.totalTokens))
  lines.push(`| **TOTAL** | | | **${totalTokens}** | **${formatCost(snapshot.totalCost)}** |`)
  lines.push('')

  // Tasks
  if (snapshot.tasks.length > 0) {
    lines.push(`## Tasks`)
    lines.push('')
    lines.push(`| # | Status | Subject | Owner |`)
    lines.push(`|---|--------|---------|-------|`)

    for (const task of snapshot.tasks) {
      lines.push(`| ${task.id} | ${task.status} | ${task.subject.slice(0, 50)} | ${task.owner || '—'} |`)
    }
    lines.push('')
  }

  // Alerts
  if (snapshot.alerts.length > 0) {
    lines.push(`## Alerts`)
    lines.push('')
    for (const alert of snapshot.alerts) {
      const time = new Date(alert.timestamp).toISOString()
      const icon = alert.level === 'critical' ? '!!' : '!'
      lines.push(`- ${icon} \`${time}\` ${alert.message}`)
    }
    lines.push('')
  }

  lines.push(`---`)
  lines.push(`*Generated by ccx v0.1.0*`)
  lines.push('')

  return lines.join('\n')
}

function formatDuration(ms: number): string {
  const s = Math.floor(ms / 1000)
  const h = Math.floor(s / 3600)
  const m = Math.floor((s % 3600) / 60)
  const sec = s % 60
  if (h > 0) return `${h}h ${m}m ${sec}s`
  if (m > 0) return `${m}m ${sec}s`
  return `${sec}s`
}
